# Generated by Django 4.2.7 on 2024-06-11 04:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.CharField(max_length=10, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=25)),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.CharField(max_length=10, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=25)),
            ],
        ),
        migrations.CreateModel(
            name='Company_details',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254)),
                ('gst_no', models.CharField(max_length=25, unique=True)),
                ('pan_no', models.CharField(max_length=10, unique=True)),
                ('address', models.TextField()),
                ('pincode', models.IntegerField()),
                ('phone_number', models.IntegerField()),
                ('tc1', models.CharField(max_length=50, null=True)),
                ('password', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('pan_no', models.CharField(max_length=10)),
                ('aadhar_no', models.CharField(max_length=12)),
                ('email', models.EmailField(max_length=254)),
                ('mobile_no', models.CharField(max_length=15)),
                ('current_address', models.TextField()),
                ('address', models.CharField(max_length=255)),
                ('city', models.CharField(max_length=100)),
                ('state', models.CharField(max_length=100)),
                ('pin_code', models.CharField(max_length=10)),
                ('customer_id', models.CharField(max_length=10)),
                ('gst_no', models.CharField(max_length=15)),
                ('username', models.CharField(max_length=100)),
                ('password', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.CharField(max_length=25, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gender', models.CharField(max_length=10, null=True)),
                ('First_name', models.CharField(max_length=25)),
                ('last_name', models.CharField(max_length=25)),
                ('date_of_birth', models.DateField()),
                ('email', models.EmailField(max_length=254)),
                ('address', models.TextField()),
                ('phone_number', models.IntegerField()),
                ('designation', models.CharField(max_length=25)),
                ('date_of_joining', models.DateField()),
                ('image', models.ImageField(upload_to='')),
                ('password', models.CharField(max_length=25)),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='IMS_Admin.department')),
            ],
        ),
        migrations.CreateModel(
            name='invoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invoice_date', models.DateField()),
                ('due_date', models.DateField()),
                ('total_amount', models.DecimalField(decimal_places=3, editable=False, max_digits=15)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='IMS_Admin.customer')),
            ],
        ),
        migrations.CreateModel(
            name='manufacturer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Company_Name', models.CharField(max_length=100, unique=True)),
                ('email', models.EmailField(max_length=254)),
                ('contact_number', models.CharField(max_length=15)),
                ('gstin_number', models.CharField(max_length=15)),
                ('pan_number', models.CharField(max_length=10)),
                ('address', models.TextField()),
                ('bank_account_number', models.CharField(max_length=20)),
                ('ifsc_code', models.CharField(max_length=20)),
                ('bank_name', models.CharField(max_length=100)),
                ('business_type', models.CharField(choices=[('Private Limited Company', 'Private Limited Company'), ('Public Limited Company', 'Public Limited Company'), ('Partnership', 'Partnership'), ('Sole Proprietorship', 'Sole Proprietorship'), ('Limited Liability Partnership (LLP)', 'Limited Liability Partnership (LLP)')], max_length=50)),
                ('business_license_number', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_date', models.DateField(auto_now_add=True)),
                ('invoice_generated', models.BooleanField(default=False)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='IMS_Admin.customer')),
                ('sales_employee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='IMS_Admin.employee')),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('product_id', models.CharField(max_length=10, primary_key=True, serialize=False, unique=True)),
                ('product_name', models.CharField(max_length=255)),
                ('sku', models.CharField(max_length=100)),
                ('unit', models.CharField(default='Piece', max_length=50)),
                ('weight', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('weight_unit', models.CharField(default='kg', max_length=10)),
                ('length', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('width', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('height', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('dimension_unit', models.CharField(default='cm', max_length=10)),
                ('cost_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('selling_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('upc', models.CharField(max_length=255, unique=True)),
                ('ean', models.CharField(max_length=255, unique=True)),
                ('mpn', models.CharField(max_length=255, unique=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='product_images/')),
                ('description', models.TextField()),
                ('is_available', models.BooleanField(default=True)),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='IMS_Admin.brand')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='IMS_Admin.category')),
                ('manufacturer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='IMS_Admin.manufacturer')),
            ],
        ),
        migrations.CreateModel(
            name='warehouse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('upc', models.CharField(blank=True, max_length=255, null=True, verbose_name='UPC (Universal Product Code)')),
                ('mpn', models.CharField(blank=True, max_length=255, null=True, verbose_name='MPN (Manufacturer Part Number)')),
                ('ean', models.CharField(blank=True, max_length=255, null=True, verbose_name='EAN (European Article Number)')),
                ('stock_status', models.BooleanField(default=True, verbose_name='Stock Status (In Stock)')),
                ('stock_number', models.IntegerField(default=0, verbose_name='Stock Number')),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='IMS_Admin.brand')),
                ('manufacturer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='IMS_Admin.manufacturer', to_field='Company_Name')),
                ('product_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='IMS_Admin.product')),
            ],
        ),
        migrations.CreateModel(
            name='OrderDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField()),
                ('description', models.CharField(max_length=255)),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('discount', models.DecimalField(decimal_places=2, max_digits=5)),
                ('tax_type', models.CharField(choices=[('ST', 'Sales Tax'), ('VAT', 'Value Added Tax'), ('ET', 'Excise Tax'), ('GST', 'Goods and Services Tax')], max_length=50)),
                ('tax_rate', models.DecimalField(decimal_places=2, editable=False, max_digits=5)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='IMS_Admin.order')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='IMS_Admin.product')),
            ],
        ),
        migrations.CreateModel(
            name='invoice_items',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cost_price', models.CharField(max_length=10)),
                ('selling_price', models.CharField(max_length=10)),
                ('net_amount', models.CharField(max_length=10)),
                ('quantity', models.IntegerField()),
                ('tax_type', models.CharField(max_length=25)),
                ('tax_rate', models.DecimalField(decimal_places=3, editable=False, max_digits=15, null=True)),
                ('tax_amount', models.DecimalField(decimal_places=3, editable=False, max_digits=15, null=True)),
                ('discount', models.DecimalField(decimal_places=3, editable=False, max_digits=15, null=True)),
                ('description', models.CharField(max_length=250)),
                ('invoice_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='IMS_Admin.invoice')),
                ('product_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='IMS_Admin.product')),
            ],
        ),
        migrations.AddField(
            model_name='invoice',
            name='order_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='IMS_Admin.order'),
        ),
        migrations.AddField(
            model_name='customer',
            name='sales_employee',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='IMS_Admin.employee'),
        ),
    ]
