# Generated by Django 5.1 on 2024-08-23 04:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('IMS_Admin', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='ean',
            new_name='hsn_code',
        ),
        migrations.RemoveField(
            model_name='product',
            name='mpn',
        ),
        migrations.RemoveField(
            model_name='product',
            name='upc',
        ),
        migrations.RemoveField(
            model_name='stock',
            name='ean',
        ),
        migrations.RemoveField(
            model_name='stock',
            name='mpn',
        ),
        migrations.RemoveField(
            model_name='stock',
            name='upc',
        ),
    ]
