# Generated by Django 5.0.1 on 2024-08-11 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('IMS_Admin', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accountspayable',
            name='balance_due',
            field=models.DecimalField(decimal_places=2, max_digits=15, null=True),
        ),
    ]
