# Generated by Django 5.0.1 on 2024-08-11 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('IMS_Admin', '0002_alter_accountspayable_balance_due'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accountspayable',
            name='balance_due',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=15),
            preserve_default=False,
        ),
    ]
