# Generated by Django 5.1 on 2024-08-23 06:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('IMS_Admin', '0002_rename_ean_product_hsn_code_remove_product_mpn_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='stock',
            old_name='product_name',
            new_name='product',
        ),
        migrations.AddField(
            model_name='restock',
            name='purchase_order',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='IMS_Admin.purchaseorder'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='restock',
            name='restocked_on',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
