# Generated by Django 5.0.1 on 2024-08-11 13:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('IMS_Admin', '0003_alter_accountspayable_balance_due'),
    ]

    operations = [
        migrations.RenameField(
            model_name='accountspayable',
            old_name='amount_due',
            new_name='total_payable_amount',
        ),
    ]
