# Generated by Django 5.1 on 2024-08-23 13:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('IMS_Admin', '0004_alter_warehouse_manager_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='StockTransferReceive',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity_received', models.PositiveIntegerField()),
                ('receive_date', models.DateTimeField(auto_now_add=True)),
                ('discrepancy_notes', models.TextField(blank=True, null=True)),
                ('destination_warehouse', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='incoming_transfers', to='IMS_Admin.warehouse')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='IMS_Admin.product')),
                ('transfer_request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='receives', to='IMS_Admin.stocktransferrequest')),
            ],
        ),
        migrations.CreateModel(
            name='StockTransferSend',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity_sent', models.PositiveIntegerField()),
                ('send_date', models.DateTimeField(auto_now_add=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='IMS_Admin.product')),
                ('source_warehouse', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='outgoing_transfers', to='IMS_Admin.warehouse')),
                ('transfer_request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sends', to='IMS_Admin.stocktransferrequest')),
            ],
        ),
    ]
