# Generated by Django 5.1 on 2024-08-24 09:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('IMS_Admin', '0005_stocktransferreceive_stocktransfersend'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='warehouse',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='IMS_Admin.warehouse'),
        ),
    ]
