# Generated by Django 5.1 on 2024-08-26 07:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('IMS_Admin', '0006_order_warehouse'),
    ]

    operations = [
        migrations.AddField(
            model_name='stocktransferreceive',
            name='damaged_stock',
            field=models.PositiveIntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='stocktransferreceive',
            name='quantity_send',
            field=models.PositiveIntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='stocktransfersend',
            name='destination_warehouse',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='incoming_transfers', to='IMS_Admin.warehouse'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='stocktransfersend',
            name='quantity_requested',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='IMS_Admin.stocktransferrequest'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='stocktransferreceive',
            name='destination_warehouse',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='incoming_stock', to='IMS_Admin.warehouse'),
        ),
        migrations.AlterField(
            model_name='stocktransferreceive',
            name='transfer_request',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='receives', to='IMS_Admin.stocktransfersend'),
        ),
    ]
