from django.urls import path
from .views import *

urlpatterns = [
    # Existing URLs
    path('', home, name='home'), 
    path('logout/', log_out, name='logout'),
    path('base', base, name='base'), 
    path('login', admin_login, name="admin_login"),
    path('add_product', add_products, name="add_product"),
    path('add_department', add_department, name="add_department"),
    path('add_employee', add_employee, name="add_employee"),
    path('add_customers', add_customer, name="add_customers"),
    path('customers', customer_table, name="customers"),
    path('add_products', add_products, name="add_products"),
    path('add_category', add_category, name="add_category"),
    path('add_brand', add_brand, name="add_brand"),
    path('add_suppliers', add_Supplier, name="add_suppliers"),
    path('products', product_table, name="products"),
    path('stockupdate', update_stock, name="stockupdate"),
    path('re_stock', re_stock, name="re_stock"),
    path('employees/', employees, name="employees"),
    path('departments', departments, name="departments"),
    path('suppliers/', suppliers, name="suppliers"),
    path('category', category, name="category"),
    path('brands', brands, name="brands"),
    path('stock', stock_table, name="stock"),
    path('restock_table', restock_table, name='restock_table'),
    path('delete_product/<str:product_id>/', delete_product, name='delete_product'),
    path('delete_customer/<str:customer_id>/', delete_customer, name='delete_customer'),
    path('delete_brand/<str:id>/', delete_brand, name='delete_brand'),
    path('delete_category/<str:id>/', delete_category, name='delete_category'),
    path('delete_employee/<str:id>/', delete_employee, name="delete_employee"),
    path('delete_department/<str:id>/', delete_department, name="delete_department"),
    path('employee/edit/<int:employee_id>/', edit_employee, name='edit_employee'),
    path('sales_cust', sales_customer_table, name="sales_cust"),
    path('generate_invoice', generate_invoice, name="generate_invoice"),
    path('orders', order_table, name="orders"),
    path('order_detail/<int:id>/', order_details, name='order_detail'),
    path('assign_sales_employee/', assign_sales_employee, name='assign_sales_employee'),
    path('delete_Supplier/<int:id>/', delete_Supplier, name='delete_Supplier'),
    path('delete_order/<int:id>/', delete_order, name="delete_order"),
    path('invoices', invoice_table, name="invoices"),
    path('delete_invoice/<int:id>/', delete_invoice, name="delete_invoice"),
    path('create_invoice/', InvoiceCreateView.as_view(), name='create_invoice'),
    path('invoice_details/<int:id>/', view_invoice, name="invoice_details"),
    path('dashboard', dashboard, name="dashboard"),
    path('edit_brand/<str:id>/', edit_brand, name='edit_brand' ),
    path('edit_category/<str:id>/', edit_category, name='edit_category' ),
    path('edit_department/<str:id>/', edit_department, name='edit_department' ),
    path('edit_employee/<str:id>/', edit_employee, name='edit_employee'),
    path('edit_manufacture/<str:id>/', edit_manufacture, name='edit_manufacture' ),
    path('edit_product/<str:product_id>/', edit_product, name='edit_product'),
    path('edit_customer/<str:customer_id>/', edit_customer, name='edit_customer'),
    path('create_order', createOrder, name="create_order"),
    path('add_customers', add_customer, name="add_customers"),
    path('edit_order/<str:order_id>/', edit_order, name="edit_order"),
    path('register/', register, name='register'),
    path('generate_invoice_pdf/<str:id>/', generate_invoice_pdf, name='generate_invoice_pdf'),
    path('edit_stock_update/<str:id>/', edit_stock_update, name='edit_stock_update'),
    path('delete_stock_update/<str:id>/', delete_stock_update, name="delete_stock_update"),

    
    # New URLs for the remaining submenu items
    
    path('create_purchase_order/', create_purchase_order, name="create_purchase_order"),
    path('purchase_orders/', manage_purchase_orders, name="purchase_orders"),
    path('purchase_order_detail/<int:order_id>/', purchase_order_detail, name='purchase_order_detail'),
    path('add_warehouse/', add_warehouse, name='add_warehouse'),
    path('get_manager_details/', get_manager_details, name='get_manager_details'),
    path('warehouses/', warehouses, name='warehouses'),
    path('warehouse/edit/<int:id>/', edit_warehouse, name='edit_warehouse'),
    path('warehouse/delete/<int:id>/', delete_warehouse, name='delete_warehouse'),
    path('low_stock_alerts/', low_stock_alerts, name="low_stock_alerts"),
    path('accounts_receivable/', accounts_receivable, name="accounts_receivable"),
    path('manage_accounts_payable/', manage_accounts_payable, name="manage_accounts_payable"),
    path('purchase_order_detail/<int:id>/', purchase_order_detail, name='purchase_order_detail'),
    path('edit_purchase_order/<int:purchase_order_id>/',edit_purchase_order, name='edit_purchase_order'),
    path('delete_purchase_orders/<str:id>/', delete_purchase_orders, name="delete_purchase_orders"),
    path('manage_accounts_receivable/', manage_accounts_receviable, name="manage_accounts_receviable"),
    path('accounts_payable', accounts_payable, name="accounts_payable"),
    path('edit_accounts_receivable/<int:id>/', edit_accounts_receviable, name="edit_accounts_receviable"),
    path('delete_manage_accounts/<str:id>/', delete_manage_accounts, name="delete_manage_accounts"),
    path('edit_accounts_payable/<int:id>/', edit_accounts_payable, name="edit_accounts_payable"),
    path('delete_accounts_payable/<str:id>/', delete_accounts_payable, name="delete_accounts_payable"),

    path('restock/edit/<int:restock_id>/', edit_restock, name='edit_restock'),
    path('restock/delete/<int:restock_id>/', delete_restock, name='delete_restock'),

    path('stock_transfer_request/', stock_transfer_request, name='stock_transfer_request'),
    path('stock_transfer_request_table/', stock_transfer_request_table, name='stock_transfer_request_table'),
    path('edit_stock_transfer_request/<int:request_id>/', edit_stock_transfer_request, name='edit_stock_transfer_request'),
    path('delete_stock_transfer_request/<int:request_id>/', delete_stock_transfer_request, name='delete_stock_transfer_request'),


    path('stock_transfer_send/', stock_transfer_send, name='stock_transfer_send'),
    path('stock_transfer_send_table/', stock_transfer_send_table, name='stock_transfer_send_table'),
    path('stock_transfer_send/edit/<int:id>/', edit_stock_transfer_send, name='edit_stock_transfer_send'),
    path('stock_transfer_send/delete/<int:id>/', delete_stock_transfer_send, name='delete_stock_transfer_send'),

    path('stock_transfer_received/', stock_transfer_received, name='stock_transfer_received'),
    path('stock_transfer_received_table/', stock_transfer_received_table, name='stock_transfer_received_table'),
    path('stock_transfer_received/edit/<int:pk>/', edit_stock_transfer_received, name='edit_stock_transfer_received'),
    path('stock_transfer_received/delete/<int:pk>/', delete_stock_transfer_received, name='delete_stock_transfer_received'),

]

